#! /usr/bin/env python3

import hmac
import base64
import secrets
import re


secret = "xyzzy"

def mkmeeting(secret):
    msg = secrets.token_bytes(6)
    h = hmac.new(bytes(secret, 'utf-8'), msg, 'sha256').digest()
    h = h[:6]

    name_bytes = msg + h

    return name_bytes.hex()

def ckmeeting(room_hex, secret):
    room = bytearray.fromhex(room_hex)
    print("raw", room)
    msg = room[0:6]
    received = room[6:]
    
    computed = hmac.new(bytes(secret, 'utf-8'), msg, 'sha256').digest()
    computed = computed[:6]
    
    return hmac.compare_digest (received, computed)
    
m = mkmeeting(secret)
print(m)
url = f"https://jitsi.pacew.org/{m}"
print(url)

print(ckmeeting(m, secret))

